version: '3.8'
services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "9000:9000"
    env_file:
      - ./backend/.env

  storefront:
    build: ./storefront
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./storefront/.env
    depends_on:
      - backend

  admin:
    build: ./admin
    restart: always
    ports:
      - "7010:80"
    env_file:
      - ./admin/.env
    depends_on:
      - backend