version: "3.8"

services:
  backend:
    image: lucasforbes1313/madi-backend:latest
    restart: always
    ports:
      - "9000:9000"
    env_file:
      - ./backend/.env

  storefront:
    image: lucasforbes1313/madi-storefront:latest
    restart: always
    ports:
      - "80:3000"
    env_file:
      - ./storefront/.env.production
    depends_on:
      - backend